In [2]:
import numpy as np
import networkx as nx

In [3]:
G = nx.Graph()

In [4]:
G.add_edge(1,3)
G.add_edge(2,3)
G.add_edge(3,5)
G.add_edge(4,5)
G.add_edge(5,6)
G.add_edge(3,8)
G.add_edge(7,8)
G.add_edge(8,9)
G.add_edge(8,10)
G.add_edge(10,11)
G.add_edge(10,12)

In [5]:
G.number_of_edges()

11

In [6]:
G.number_of_nodes()

12

In [7]:
L = np.zeros((G.number_of_nodes(), G.number_of_nodes()))

In [8]:
for i in range(G.number_of_nodes()):
    L[i][i] = G.degree[i+1]

In [9]:
for i in range(G.number_of_nodes()):
    for j in range(G.number_of_nodes()):
        if i == j:
            continue
        if G.has_edge(i+1, j+1):
            L[i][j] = -1

In [10]:
L

array([[ 1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1.,  4.,  0., -1.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1., -1.,  3., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0., -1.,  4., -1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  3., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  1.]])

In [11]:
np.linalg.eig(L)

(array([5.82842712e+00, 4.56155281e+00, 3.41421356e+00, 3.00000000e+00,
        1.22002228e-16, 1.71572875e-01, 4.38447187e-01, 5.85786438e-01,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00]),
 array([[ 1.29844172e-01,  1.30478237e-01,  9.67135681e-02,
          2.04124145e-01,  2.88675135e-01,  1.65100388e-01,
         -3.28596150e-01,  4.43315733e-01, -7.07106781e-01,
         -3.30304983e-01,  2.26042382e-01,  9.15904749e-02],
        [ 1.29844172e-01,  1.30478237e-01,  9.67135681e-02,
          2.04124145e-01,  2.88675135e-01,  1.65100388e-01,
         -3.28596150e-01,  4.43315733e-01,  7.07106781e-01,
          3.30304983e-01, -2.26042382e-01, -9.15904749e-02],
        [-6.26943121e-01, -4.64705132e-01, -2.33487208e-01,
         -4.08248290e-01,  2.88675135e-01,  1.36773640e-01,
         -1.84524092e-01,  1.83627389e-01,  6.12555837e-17,
         -4.47286217e-17,  3.06097841e-17,  1.24028274e-17],
        [-5.37832170e-02, -1.30478237e-01,  2.33487208e-01,

In [12]:
np.linalg.eig(L)[0]

array([5.82842712e+00, 4.56155281e+00, 3.41421356e+00, 3.00000000e+00,
       1.22002228e-16, 1.71572875e-01, 4.38447187e-01, 5.85786438e-01,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00])

In [13]:
np.linalg.eig(L)[1][:,0]

array([ 0.12984417,  0.12984417, -0.62694312, -0.05378322,  0.25968834,
       -0.05378322, -0.12984417,  0.62694312, -0.12984417, -0.25968834,
        0.05378322,  0.05378322])

In [13]:
np.sort(np.linalg.eig(L)[0])

array([1.22002228e-16, 1.71572875e-01, 4.38447187e-01, 5.85786438e-01,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       3.00000000e+00, 3.41421356e+00, 4.56155281e+00, 5.82842712e+00])

In [21]:
file = open('yiyang_chen_task1.txt', 'w', encoding='utf-8')
for i in range(G.number_of_nodes()):
    for j in range(G.number_of_nodes()):
        if j == 0:
            file.write(str(int(L[i][j])))
        else:
            file.write(',' + str(int(L[i][j])))
    file.write('\n')
i = 0
for num in np.linalg.eig(L)[1][:,5]:
    if i == 0:
        file.write(str(num))
        i += 1
    else:
        file.write(',' + str(num))
file.write('\n')
file.write('{1,2,3,4,5,6},{7,8,9,10,11,12}')
file.close()