In [1]:
import numpy as np
import networkx as nx
from sklearn.cluster import KMeans

In [2]:
G = nx.Graph()
G.add_edge(1,3)
G.add_edge(2,3)
G.add_edge(3,5)
G.add_edge(4,5)
G.add_edge(5,6)
G.add_edge(3,8)
G.add_edge(7,8)
G.add_edge(8,9)
G.add_edge(8,10)
G.add_edge(10,11)
G.add_edge(10,12)

In [3]:
L = np.zeros((G.number_of_nodes(), G.number_of_nodes()))
for i in range(G.number_of_nodes()):
    L[i][i] = G.degree[i+1]
for i in range(G.number_of_nodes()):
    for j in range(G.number_of_nodes()):
        if i == j:
            continue
        if G.has_edge(i+1, j+1):
            L[i][j] = -1

In [4]:
L

array([[ 1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1.,  4.,  0., -1.,  0.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1., -1.,  3., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0., -1.,  4., -1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  3., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  1.]])

In [7]:
a = np.linalg.eig(L)
a

(array([5.82842712e+00, 4.56155281e+00, 3.41421356e+00, 3.00000000e+00,
        1.22002228e-16, 1.71572875e-01, 4.38447187e-01, 5.85786438e-01,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00]),
 array([[ 1.29844172e-01,  1.30478237e-01,  9.67135681e-02,
          2.04124145e-01,  2.88675135e-01,  1.65100388e-01,
         -3.28596150e-01,  4.43315733e-01, -7.07106781e-01,
         -3.30304983e-01,  2.26042382e-01,  9.15904749e-02],
        [ 1.29844172e-01,  1.30478237e-01,  9.67135681e-02,
          2.04124145e-01,  2.88675135e-01,  1.65100388e-01,
         -3.28596150e-01,  4.43315733e-01,  7.07106781e-01,
          3.30304983e-01, -2.26042382e-01, -9.15904749e-02],
        [-6.26943121e-01, -4.64705132e-01, -2.33487208e-01,
         -4.08248290e-01,  2.88675135e-01,  1.36773640e-01,
         -1.84524092e-01,  1.83627389e-01,  6.12555837e-17,
         -4.47286217e-17,  3.06097841e-17,  1.24028274e-17],
        [-5.37832170e-02, -1.30478237e-01,  2.33487208e-01,

In [6]:
t = np.zeros((G.number_of_nodes(), 3))

In [8]:
j = 0
for val in a[1][:,5]:
    t[j][0] = val
    j += 1
j = 0
for val in a[1][:,6]:
    t[j][1] = val
    j += 1
j = 0
for val in a[1][:,7]:
    t[j][2] = val
    j += 1


In [9]:
t

array([[ 0.16510039, -0.32859615,  0.44331573],
       [ 0.16510039, -0.32859615,  0.44331573],
       [ 0.13677364, -0.18452409,  0.18362739],
       [ 0.3985876 ,  0.32859615, -0.18362739],
       [ 0.33020078,  0.18452409, -0.07606095],
       [ 0.3985876 ,  0.32859615, -0.18362739],
       [-0.16510039, -0.32859615, -0.44331573],
       [-0.13677364, -0.18452409, -0.18362739],
       [-0.16510039, -0.32859615, -0.44331573],
       [-0.33020078,  0.18452409,  0.07606095],
       [-0.3985876 ,  0.32859615,  0.18362739],
       [-0.3985876 ,  0.32859615,  0.18362739]])

In [10]:
a[1][:,1]

array([ 0.13047824,  0.13047824, -0.46470513, -0.13047824,  0.46470513,
       -0.13047824,  0.13047824, -0.46470513,  0.13047824,  0.46470513,
       -0.13047824, -0.13047824])

In [11]:
kmeans = KMeans(n_clusters=4, random_state=0).fit(t)

In [12]:
kmeans.labels_

array([2, 2, 2, 0, 0, 0, 3, 3, 3, 1, 1, 1])

In [13]:
c = kmeans.cluster_centers_
c

array([[ 0.37579199,  0.28057213, -0.14777191],
       [-0.37579199,  0.28057213,  0.14777191],
       [ 0.15565814, -0.28057213,  0.35675295],
       [-0.15565814, -0.28057213, -0.35675295]])

In [14]:
file = open('yiyang_chen_task2.txt', 'w', encoding='utf-8')
for l in t:
    for i in range(3):
        if i == 0:
            file.write(str(l[i]))
        else:
            file.write(',' + str(l[i]))
    file.write('\n')
for l in c:
    for i in range(3):
        if i == 0:
            file.write(str(l[i]))
        else:
            file.write(',' + str(l[i]))
    file.write('\n')
file.write('{1,2,3},{4,5,6},{7,8,9},{10,11,12}')
file.close()